### PR TITLE
3.0

### LINKED ISSUE #1: add a DatabaseComponent
You should be able to manage notifications in a database.

### LINKED ISSUE #2: Add Nexmo comonent for text messaging

### PR DESCRIPTION
**Pull request by girardinsamuel**
**⚠️ This refactoring will be integrated directly into Masonite 4 core !**. This repo won't be used anymore from Masonite 4.

## Refactoring
- migration to Masonite 3
- usual package refactoring as in other repos (github actions, badges on readme etc ...)
- architecture refactoring

## New features 

- Add a new `database` driver to save notifications in database
- Add a new `broadcast` driver to broadcast notifications
- Add a new `vonage` driver with Vonage(Nexmo) SMS service => after this one all others will be in external packages.
- Add a `Notifiable` mixin to set app models notifiable (such as User).
- Update the `mail` and `slack` driver to be more flexible
- Drop attachments in favor of blocks for Slack notif creation (as attachments will be deprecated)
- Add a way to send notifications to not Notifiable entity aka AnonymousUsers
- Add a way to ignore_errors when sending
- Refactor dry to send notifications without actually sending
- Add unit tests for core features and all drivers
- Add Custom notification class creation and use as any drivers
- Add channels override on the fly 
- ~~Add Event handling with `masonite-events`~~ => in an other PR later

## Documentation
has been entirely rewritten and available MasoniteFramework/docs#131

Fixes #2
Fixes #1

### CODE REVIEW

**Comment by girardinsamuel** [comment]
All tests are passing excepting ones for broadcast which are fixed in a PR in masonite repo.

**Comment by josephmancuso** [comment]
@girardinsamuel looks like this needs to be updated for Masonite ORM? I see orator issues in the tests

**Comment by girardinsamuel** [comment]
Yeah I have to migrate to Masonite ORM, and test a bit the features.

Also I need to continue updating documentation in the related PR.

**Comment by josephmancuso** [comment]
Ok awesome. I discovered a way to see all pull requests in an organization lol. So I found this one from October of 2020 .. lol. 

https://github.com/pulls

Can add whatever filters you need in the filter bar

**Comment by girardinsamuel** [comment]
@josephmancuso I have completed to refactor this package for 3.0 and to add features.

- I have updated nearly all masonite notifications documentation (just have to document broadcasting notifications)
- I have tested the different notifications channels and the general behaviour on a local project

It was a big work, hope you'll like this 💪 🚀 

_Maybe after releasing this we should integrate this package into Masonite core, this should be quick._

**Pull request closed without merging**
